apiVersion: apps/v1
kind: Deployment
metadata:
  name: splashpage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splashpage
  template:
    metadata:
      labels:
        app: splashpage
    spec:
      containers:
      - name: splashpage-container
        image: soaresricardo/splashpage:tagname
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: splashpage-service
spec:
  type: NodePort
  selector:
    app: splashpage
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30000